Repository MattEzekiel/macon, pull requests merged in 2025-04, with the labels that each got.

#9 added file-size
  app/Http/Controllers/FilesController.php
  app/Models/Files.php
  database/migrations/2025_04_08_222508_add_filesize_column_to_files_table.php
  resources/views/admin/files/forms/name-file.blade.php
Labels: enhancement, fix

#10 Fix seeder
  app/Models/Admin.php
  database/seeders/AdminSeeder.php
Labels: fix

#12 Trabajo en Issues #3 y #4
  app/Http/Controllers/QRController.php
  resources/views/admin/qr/index.blade.php
  resources/views/links.blade.php
Labels: enhancement, fix

#19 Feature/añadido de tablas
  app/Http/Controllers/ClientsController.php
  app/Http/Controllers/ProductsController.php
  app/Http/Controllers/QRController.php
  app/Models/Clients.php
  app/Models/Products.php
  app/Models/QRs.php
  lang/en/clients.php
  lang/en/products.php
  lang/es/clients.php
  lang/es/products.php
  resources/views/admin/clients/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/qr/index.blade.php
Labels: enhancement

#20 Persistencia de archivos
  resources/views/admin/files/edit-file.blade.php
  resources/views/admin/files/forms/store-file.blade.php
  resources/views/admin/files/new-file.blade.php
Labels: enhancement

#15 Mejoras en el diseño de pantalla QR's
  app/Http/Controllers/FilesController.php
  resources/views/layouts/general.blade.php
  resources/views/links.blade.php
Labels: enhancement

#39 Production
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/FilesController.php
  app/Http/Controllers/QRController.php
  app/Models/Clients.php
  app/Models/Files.php
  app/Traits/FileSizeFormatter.php
  database/migrations/2025_04_14_152945_add_visits_count_to_qr_table.php
  database/migrations/2025_04_14_153013_add_visits_count_to_files_table.php
  resources/views/admin/dashboard.blade.php
  resources/views/components/icons/file-icon.blade.php
  resources/views/components/icons/weight-icon.blade.php
  resources/views/layouts/general.blade.php
  resources/views/links.blade.php
  routes/web.php
Labels: enhancement

#40 Mejoras en las vistas de preview de archivo #21
  resources/views/admin/files/edit-file.blade.php
  resources/views/admin/files/forms/store-file.blade.php
Labels: fix

#51 Implementación de botones submit #36
  app/View/Components/Forms/SubmitButton.php
  resources/views/components/forms/submit-button.blade.php
Labels: enhancement, javascript

#55 added top clients for users on dashboard
  app/Http/Controllers/AdminController.php
  app/Models/Clients.php
  app/Models/User.php
  resources/views/admin/dashboard.blade.php
Labels: enhancement

#56 Aplicadas las traducciones #22 , cambio de idioma #23 y #57 de submit buttons
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/FilesController.php
  app/Http/Controllers/QRController.php
  app/Http/Middleware/Admin.php
  app/Models/Clients.php
  app/Models/Files.php
  app/Models/Products.php
  app/Models/User.php
  lang/en/auth.php
  lang/en/clients.php
  lang/en/dashboard.php
  lang/en/files.php
  lang/en/general.php
  lang/en/products.php
  lang/en/qrs.php
  lang/en/users.php
  lang/es/auth.php
  lang/es/clients.php
  lang/es/dashboard.php
  lang/es/files.php
  lang/es/general.php
  lang/es/products.php
  lang/es/qrs.php
  lang/es/users.php
  resources/views/admin/clients/edit-client.blade.php
  resources/views/admin/clients/forms/store-client.blade.php
  resources/views/admin/clients/index.blade.php
  resources/views/admin/clients/new-client.blade.php
  resources/views/admin/contacto/index.blade.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/files/edit-file.blade.php
  resources/views/admin/files/forms/name-file.blade.php
  resources/views/admin/files/forms/store-file.blade.php
  resources/views/admin/files/index.blade.php
  resources/views/admin/files/name-file.blade.php
  resources/views/admin/files/new-file.blade.php
  resources/views/admin/forgot-password.blade.php
  resources/views/admin/login.blade.php
  resources/views/admin/products/edit-product.blade.php
  resources/views/admin/products/forms/store-product.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/products/new-product.blade.php
  resources/views/admin/qr/forms/store-qr.blade.php
  resources/views/admin/qr/index.blade.php
  resources/views/admin/qr/new-qr.blade.php
  resources/views/admin/reset-password.blade.php
  resources/views/admin/users/edit-user.blade.php
  resources/views/admin/users/forms/store-user.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/admin/users/new-user.blade.php
  resources/views/components/admin/footer.blade.php
  resources/views/components/admin/sidebar.blade.php
  resources/views/components/forms/file-input.blade.php
  resources/views/components/forms/floating-select.blade.php
  resources/views/components/language-selector.blade.php
  resources/views/layouts/auth.blade.php
  routes/web.php
Labels: enhancement

#58 Aplicación de Buscar valores desde la tabla #27
  app/Http/Controllers/ProductsController.php
  resources/views/admin/clients/index.blade.php
  resources/views/admin/files/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/qr/index.blade.php
Labels: enhancement

#59 Fix ping
  bootstrap/app.php
  lang/en/general.php
  lang/es/general.php
  resources/views/layouts/general.blade.php
  resources/views/links.blade.php
  routes/web.php
Labels: fix
