Repository MattEzekiel/macon, pull requests merged in 2025-05, with the labels that each got.

#67 save files for bucket in production and local
  app/Http/Controllers/FilesController.php
  app/Http/Controllers/QRController.php
  app/Models/QRs.php
  composer.json
  composer.lock
  database/migrations/2025_05_02_214248_add_link_to__q_r_table.php
  lang/en/qrs.php
  lang/es/qrs.php
  resources/views/admin/files/edit-file.blade.php
  resources/views/admin/files/forms/name-file.blade.php
  resources/views/admin/files/index.blade.php
  resources/views/admin/qr/forms/store-qr.blade.php
  resources/views/admin/qr/index.blade.php
  resources/views/components/admin/sidebar.blade.php
  resources/views/links.blade.php
  routes/web.php
Labels: fix

#70 Security composer
  composer.lock
Labels: fix, php

#71 Correcciones para Fill inputs #28
  composer.lock
  package-lock.json
  package.json
  resources/views/admin/clients/forms/searcher.blade.php
  resources/views/admin/files/forms/searcher.blade.php
  resources/views/admin/products/forms/searcher.blade.php
  resources/views/admin/qr/forms/searcher.blade.php
  resources/views/admin/qr/index.blade.php
  resources/views/admin/users/forms/searcher.blade.php
Labels: fix

#74 buttons
  app/View/Components/Forms/SubmitButton.php
  resources/views/admin/products/forms/store-product.blade.php
Labels: fix

#77 Dev
  app/Http/Controllers/ProductsController.php
  resources/views/admin/products/forms/store-product.blade.php
  resources/views/components/forms/submit-button.blade.php
Labels: fix

#75 Modificación de la vista Links de QR's #72
  app/Http/Controllers/FilesController.php
  lang/en/files.php
  lang/es/files.php
  package-lock.json
  package.json
  public/js/pdf.worker.js
  resources/js/app.js
  resources/views/admin/files/view.blade.php
  resources/views/links.blade.php
  routes/web.php
Labels: enhancement, fix

#79 PROD merge to DEV
  app/Http/Controllers/FilesController.php
  lang/en/files.php
  lang/es/files.php
  package-lock.json
  package.json
  public/js/pdf.worker.js
  resources/js/app.js
  resources/views/admin/files/view.blade.php
  resources/views/links.blade.php
  routes/web.php
Labels: enhancement, fix

#90 Dev to prod
  app/Http/Controllers/ContactController.php
  app/Http/Controllers/FilesController.php
  app/Http/Controllers/ProductsController.php
  app/Http/Controllers/QRController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/Client.php
  app/Models/Contact.php
  app/Models/Products.php
  app/Models/QRs.php
  bootstrap/app.php
  database/migrations/2025_05_23_234400_create_contact_table.php
  lang/en/dashboard.php
  lang/en/general.php
  lang/en/products.php
  lang/en/users.php
  lang/es/dashboard.php
  lang/es/general.php
  lang/es/products.php
  lang/es/users.php
  package-lock.json
  package.json
  resources/views/admin/contacto/index.blade.php
  resources/views/admin/contacto/show.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/qr/forms/store-qr.blade.php
  resources/views/client/contacto/forms/index.blade.php
  resources/views/client/contacto/index.blade.php
  resources/views/client/dashboard.blade.php
  resources/views/client/files/edit-file.blade.php
  resources/views/client/files/forms/name-file.blade.php
  resources/views/client/files/forms/searcher.blade.php
  resources/views/client/files/forms/store-file.blade.php
  resources/views/client/files/index.blade.php
  resources/views/client/files/name-file.blade.php
  resources/views/client/files/new-file.blade.php
  resources/views/client/files/view.blade.php
  resources/views/client/login.blade.php
  resources/views/client/products/edit-product.blade.php
  resources/views/client/products/forms/searcher.blade.php
  resources/views/client/products/forms/store-product.blade.php
  resources/views/client/products/index.blade.php
  resources/views/client/products/new-product.blade.php
  resources/views/client/qr/forms/searcher.blade.php
  resources/views/client/qr/forms/store-qr.blade.php
  resources/views/client/qr/index.blade.php
  resources/views/client/qr/new-qr.blade.php
  resources/views/client/users/edit-user.blade.php
  resources/views/client/users/forms/searcher.blade.php
  resources/views/client/users/forms/store-user.blade.php
  resources/views/client/users/index.blade.php
  resources/views/client/users/new-user.blade.php
  resources/views/components/admin/sidebar.blade.php
  resources/views/components/forms/floating-textarea.blade.php
  resources/views/components/language-selector.blade.php
  resources/views/components/tabler-logout.blade.php
  routes/web.php
Labels: enhancement

#91 Translate pagination #86
  lang/en/pagination.php
  lang/es/pagination.php
  resources/views/vendor/pagination/bootstrap-4.blade.php
  resources/views/vendor/pagination/bootstrap-5.blade.php
  resources/views/vendor/pagination/default.blade.php
  resources/views/vendor/pagination/semantic-ui.blade.php
  resources/views/vendor/pagination/simple-bootstrap-4.blade.php
  resources/views/vendor/pagination/simple-bootstrap-5.blade.php
  resources/views/vendor/pagination/simple-default.blade.php
  resources/views/vendor/pagination/simple-tailwind.blade.php
  resources/views/vendor/pagination/tailwind.blade.php
Labels: enhancement

#93 Actualización de pdfjs-dist #87
  package-lock.json
  package.json
Labels: fix
